#include <CDP2QtLib.h>
#include <CDPBaseWidgetsLib.h>
#include <cdpgraphwidgetslib.h>
#include <CDPEventListLib.h>
#include <cdpeventmanager.h>
#include <kinematics.h>
#include <securitylib.h>
#include <sequencer.h>
#include <StudioAPIServerLib.h>
#include <automation.h>
